// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJLnUZQveJm9tA5EjZpSYFRTV9RcWn18A',
    appId: '1:206439705608:web:0af0fe41e373fac3a675bd',
    messagingSenderId: '206439705608',
    projectId: 'market-mobile-27138',
    authDomain: 'market-mobile-27138.firebaseapp.com',
    storageBucket: 'market-mobile-27138.firebasestorage.app',
    measurementId: 'G-H49X4L78EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaOedckIo0fw5XqvtL6w5eVFFIh15mqOk',
    appId: '1:206439705608:android:787277e0f2dc054da675bd',
    messagingSenderId: '206439705608',
    projectId: 'market-mobile-27138',
    storageBucket: 'market-mobile-27138.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_hsDLvKLJxvuWW8dWA7hB1_fQHApbklM',
    appId: '1:206439705608:ios:9e4d469e00b5f623a675bd',
    messagingSenderId: '206439705608',
    projectId: 'market-mobile-27138',
    storageBucket: 'market-mobile-27138.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_hsDLvKLJxvuWW8dWA7hB1_fQHApbklM',
    appId: '1:206439705608:ios:9e4d469e00b5f623a675bd',
    messagingSenderId: '206439705608',
    projectId: 'market-mobile-27138',
    storageBucket: 'market-mobile-27138.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJLnUZQveJm9tA5EjZpSYFRTV9RcWn18A',
    appId: '1:206439705608:web:885b43fcda1b5175a675bd',
    messagingSenderId: '206439705608',
    projectId: 'market-mobile-27138',
    authDomain: 'market-mobile-27138.firebaseapp.com',
    storageBucket: 'market-mobile-27138.firebasestorage.app',
    measurementId: 'G-KD4XC4VKM7',
  );
}
